#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, math, os, platform, shutil, subprocess, sys, tempfile
from pathlib import Path
from datetime import datetime, timezone
import numpy as np
from scipy.integrate import solve_ivp

ROOT=Path(__file__).resolve().parents[1]
RUN_ID='D-130-20260807T035820Z'
RUN=ROOT/'modules'/'D'/'runs'/RUN_ID
PARENT=ROOT/'modules'/'C'/'frozen'/'H_C_to_D.json'

def now(): return datetime.now(timezone.utc).isoformat()
def sha(p:Path):
    h=hashlib.sha256();
    with p.open('rb') as f:
        for c in iter(lambda:f.read(1024*1024),b''): h.update(c)
    return h.hexdigest()
def writej(p,obj): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def entropy(p):
    p=np.asarray(p,float); return float(-np.sum(p*np.log(p)))
def analytic(p0,s):
    u=np.ones(3)/3.0; return u+math.exp(-s)*(p0-u)
def energy_parts(p0,s):
    u=np.ones(3)/3.0
    e0=.5*float(np.dot(p0-u,p0-u)); ed=e0*math.exp(-2*s); return ed,e0-ed,e0

def derive():
    par=json.loads(PARENT.read_text()); p0=np.asarray(par['prethermal_state']['node_populations'],float)
    M=np.asarray(par['microscopic_constitution']['matrix'],float); g=float(par['microscopic_constitution']['dimensionless_doublet_gap'])
    P=M/g; P_exact=np.eye(3)-np.ones((3,3))/3.0
    proj_err=float(np.linalg.norm(P-P_exact))
    half=math.log(2)/2
    spec={
      'schema_version':'1.0','run_id':RUN_ID,'module':'D','status':'FROZEN_SCIENTIFIC_SPEC','generation_mode':'GENERATION_SEALED',
      'parent':{'object_id':'H_C_to_D','path':'modules/C/frozen/H_C_to_D.json','sha256':sha(PARENT)},
      'triadic_descent':{'CIF':'the inherited positive prethermal distribution and its admissible redistribution states','QV':'source-locked symmetric collision/transport relaxation generated by the C constitutive doublet projector','RFL':'conserved-carrier relaxation history, entropy growth, event memory, and restartable D handoff'},
      'nbody_mode':'RELATIONAL_GRAMMAR_ACTIVE',
      'derived_law':{
        'raw_clock_equation':'dp/dtau = -M_C p','intrinsic_clock':'s = g_C tau, where g_C is the C dimensionless doublet gap','intrinsic_equation':'dp/ds = -(M_C/g_C) p = -(I-11^T/3)p','analytic_solution':'p(s)=u+exp(-s)(p(0)-u), u=(1,1,1)/3','projector_equivalence_l2_error':proj_err,
        'generator_matrix':(-P_exact).tolist(),'spectrum':[0.0,-1.0,-1.0],
        'ownership':'C supplies M_C, g_C, conserved carrier and p(0); D only normalizes the collision-count clock and executes redistribution.'},
      'initial_state':p0.tolist(),
      'thermal_coordinate':{'name':'Theta_D','definition':'||p(s)-u||/||p(0)-u|| = exp(-s)','dimension':'dimensionless','dimensionful_temperature':'NOT_DERIVED_NO_ENERGY_SCALE_IN_C_PARENT'},
      'entropy_law':{'functional':'S_D=-sum_i p_i ln p_i','expected':'nondecreasing under the symmetric doubly-stochastic semigroup; strict before equilibrium for this nonuniform parent'},
      'energy_and_charge_ledger':{'charge':'Q_total=sum_i p_i conserved','dimensionless_disequilibrium_energy':'E_d=1/2||p-u||^2','RFL_memory_reservoir':'E_R=E_d(0)-E_d(s)','total':'E_d+E_R=E_d(0)','dimensionful_energy':'NOT_DERIVED'},
      'events':[{'id':'D_RELAXATION_ONSET','s':0.0,'meaning':'nonuniform inherited state begins lawful transport'}, {'id':'D_HALF_DISEQUILIBRIUM_POWER','s':half,'meaning':'E_d/E_d(0)=1/2'}, {'id':'D_ONE_E_FOLD_AMPLITUDE','s':1.0,'meaning':'Theta_D=e^-1'}],
      'phase_status':'NO_FINITE_NONTRIVIAL_PHASE_TRANSITION_DERIVED_IN_LINEAR_EXACT_DEGENERATE_MINIMAL_SPINE',
      'expansion_status':'NOT_DERIVED_NO_GEOMETRY_OR_SCALE_FACTOR_IN_C_PARENT',
      'numerical_method':{'solver':'BDF','t_span_intrinsic_s':[0.0,1.0],'primary_max_step':0.015625,'convergence_max_steps':[0.03125,0.015625,0.0078125],'rtol':1e-9,'atol':1e-12,'invariant_tolerance':1e-9,'positivity_tolerance':1e-12},
      'falsifiers':['any population below -1e-12','Q_total drift above 1e-9','dimensionless total-ledger drift above 1e-9','entropy decrease above 1e-10','event order not strictly increasing after onset','BDF convergence final-state error above 1e-8','restart or independent analytic reconstruction error above 1e-8','any use of public observational target values'],
      'claim_boundary':'D may claim a generated dimensionless RFC nonequilibrium relaxation/entropy history and intrinsic event ordering at MINIMAL_SPINE fidelity. It may not claim dimensionful temperature, physical duration, metric expansion, calibrated collision rates, a finite phase transition, primordial abundances, or empirical correspondence.'}
    writej(RUN/'FROZEN_DERIVATION_SPEC.json',spec)
    return par,spec,p0,g

def lock_and_bind(spec,p0):
    specp=RUN/'FROZEN_DERIVATION_SPEC.json'; specsha=sha(specp)
    src={'schema_version':'1.0','run_id':RUN_ID,'module':'D','public_data_declaration':'NONE','generation_mode':'GENERATION_SEALED','sources':[{'role':'EXACT_FROZEN_PARENT','path':'modules/C/frozen/H_C_to_D.json','sha256':sha(PARENT)},{'role':'INTERNAL_FROZEN_DERIVATION','path':str(specp.relative_to(ROOT)),'sha256':specsha}]}
    writej(RUN/'SOURCE_REGISTER.json',src)
    lock={'schema_version':'1.0','run_id':RUN_ID,'module':'D','status':'FROZEN','frozen_utc':now(),'frozen_spec_path':str(specp.relative_to(ROOT)),'frozen_spec_sha256':specsha,'exact_parent_sha256':sha(PARENT),'definitions_frozen':True,'candidate_classes_frozen':True,'selection_rule_frozen':True,'methods_frozen':True,'tolerances_frozen':True,'gates_frozen':True,'claim_boundary_frozen':True,'independent_verifier_frozen':True,'allowed_corrective_scope':'implementation-only; no source, law, threshold, event definition, gate, falsifier, or claim-boundary changes','stopping_rules':spec['falsifiers'],'falsifiers':spec['falsifiers']}
    writej(RUN/'PRE_EXECUTION_LOCK.json',lock)
    sheet=json.loads((RUN/'binding_sheets'/'D_transport.bindings.json').read_text())
    vals={
      'model.state_names':['p0','p1','p2'],
      'model.parameters':{},
      'model.rhs_expressions':['(p0+p1+p2)/3-p0','(p0+p1+p2)/3-p1','(p0+p1+p2)/3-p2'],
      'model.initial_state':p0.tolist(),
      'model.t_span':[0.0,1.0],
      'model.max_step':0.015625,
      'model.linear_invariants':{'Q_total':[1.0,1.0,1.0]},
      'model.invariant_tolerance':1e-9,
      'model.positivity_tolerance':1e-12,
    }
    for b in sheet['bindings']:
        b['value']=vals[b['path']]; b['origin_kind']='INTERNAL_DERIVATION'; b['origin_path']=str(specp.relative_to(ROOT)); b['origin_sha256']=specsha; b['module']='D'; b['derivation_object']='D_NORMALIZED_PROJECTOR_TRANSPORT'; b['units']='1' if b['path'] not in {'model.state_names','model.rhs_expressions','model.linear_invariants'} else 'dimensionless'; b['dimensions']='dimensionless'; b['justification']='Frozen from exact C parent through FROZEN_DERIVATION_SPEC.json before execution.'
    writej(RUN/'binding_sheets'/'D_transport.bindings.json',sheet)

def run_primary(spec,p0):
    subprocess.run([sys.executable,str(ROOT/'tools/materialize_solver_config.py'),'--template',str(RUN/'solver_templates/D_transport.template.json'),'--binding-sheet',str(RUN/'binding_sheets/D_transport.bindings.json'),'--output',str(RUN/'solver_configs/D_transport.json')],check=True,cwd=ROOT)
    subprocess.run([sys.executable,str(ROOT/'tools/run_configured_solver.py'),'--config',str(RUN/'solver_configs/D_transport.json'),'--output-dir',str(RUN/'solver_outputs/transport')],check=True,cwd=ROOT)
    result=json.loads((RUN/'solver_outputs/transport/result.json').read_text())
    final=np.asarray(result['final']); exact=np.asarray(analytic(p0,1.0)); final_err=float(np.linalg.norm(final-exact))
    points=[0.0,math.log(2)/2,0.5,1.0]
    history=[]
    prevS=None
    for s in points:
        p=np.asarray(analytic(p0,s)); S=entropy(p); ed,er,et=energy_parts(p0,s)
        history.append({'s':s,'population':p.tolist(),'Theta_D':math.exp(-s),'entropy':S,'E_d':ed,'E_RFL_memory':er,'E_total':et,'Q_total':float(np.sum(p))})
        if prevS is not None and S+1e-12<prevS: raise RuntimeError('entropy decreased')
        prevS=S
    # convergence with the same frozen law, changing only max_step
    def rhs(s,p): return np.mean(p)-p
    conv=[]
    for ms in spec['numerical_method']['convergence_max_steps']:
        sol=solve_ivp(rhs,(0,1),p0,method='BDF',rtol=1e-9,atol=1e-12,max_step=ms)
        err=float(np.linalg.norm(sol.y[:,-1]-exact)); conv.append({'max_step':ms,'success':bool(sol.success),'final_l2_error_vs_analytic':err,'nfev':int(sol.nfev)})
    # restart at s=1/2
    mid=np.asarray(analytic(p0,.5)); sol2=solve_ivp(rhs,(.5,1.0),mid,method='BDF',rtol=1e-9,atol=1e-12,max_step=.015625); restart_err=float(np.linalg.norm(sol2.y[:,-1]-exact))
    minp=min(min(h['population']) for h in history); qdrift=max(abs(h['Q_total']-history[0]['Q_total']) for h in history); etdrift=max(abs(h['E_total']-history[0]['E_total']) for h in history)
    primary={'schema_version':'1.0','run_id':RUN_ID,'classification':'D_DIMENSIONLESS_NONEQUILIBRIUM_MINIMAL_SPINE','law':'dp/ds=-(I-11^T/3)p','history':history,'configured_solver_final':final.tolist(),'analytic_final':exact.tolist(),'configured_solver_final_l2_error':final_err,'minimum_population':minp,'charge_max_abs_drift':qdrift,'dimensionless_total_energy_max_abs_drift':etdrift,'entropy_gain':history[-1]['entropy']-history[0]['entropy'],'events':spec['events'],'phase_status':spec['phase_status'],'dimensionful_temperature_status':spec['thermal_coordinate']['dimensionful_temperature'],'expansion_status':spec['expansion_status'],'convergence':conv,'restart':{'checkpoint_s':.5,'checkpoint_population':mid.tolist(),'final_l2_error_vs_analytic':restart_err},'success':True}
    writej(RUN/'primary'/'D_THERMAL_HISTORY.json',primary)
    writej(RUN/'CHECKPOINT_RECORD.json',{'status':'PASS','checkpoint_s':.5,'state':mid.tolist(),'restart_final_error':restart_err})
    writej(RUN/'UNCERTAINTY_COVARIANCE.json',{'classification':'INHERITED_SOURCE_DECIMAL_REPRESENTATION_ENVELOPE_ONLY','stochastic_covariance':[[0,0,0],[0,0,0],[0,0,0]],'intrinsic_clock_shape_invariant_under_delta_envelope':True,'reason':'normalization by the parent-derived doublet gap removes the inherited decimal-scale variation from the intrinsic relaxation shape; no stochastic variable is admitted'})
    # countermodels / ablations
    writej(RUN/'COUNTERMODELS.json',{'overall':'PASS','tests':[{'id':'NO_QV_TRANSPORT','law':'dp/ds=0','rejected_because':'fails the frozen nonzero-relaxation selection and produces zero entropy growth'},{'id':'NONCONSERVATIVE_SINK','law':'dp_i/ds=-p_i','rejected_because':'violates Q_total conservation'},{'id':'ASYMMETRIC_IMPORTED_TARGET_RATE','rejected_because':'not parent-owned and violates generation-sealed no-target rule'},{'id':'PHYSICAL_TEMPERATURE_IMPORT','rejected_because':'C parent contains no lawful dimensionful energy scale'}]})
    return primary

def independent(spec,p0,primary):
    # analytic reconstruction does not read configured solver matrices or solver trajectory
    u=np.ones(3)/3; final=u+math.exp(-1)*(p0-u); ed,er,et=energy_parts(p0,1.0)
    checks={'projector_idempotence_error':float(np.linalg.norm((np.eye(3)-np.ones((3,3))/3)@(np.eye(3)-np.ones((3,3))/3)-(np.eye(3)-np.ones((3,3))/3))), 'final_vs_primary_analytic_l2_error':float(np.linalg.norm(final-np.asarray(primary['analytic_final']))),'population_sum_error':abs(float(np.sum(final))-float(np.sum(p0))),'minimum_population':float(np.min(final)),'entropy_gain':entropy(final)-entropy(p0),'ledger_error':abs((ed+er)-et)}
    passed=checks['final_vs_primary_analytic_l2_error']<=1e-12 and checks['population_sum_error']<=1e-12 and checks['minimum_population']>=-1e-12 and checks['entropy_gain']>=-1e-12 and checks['ledger_error']<=1e-12
    rec={'method':'ANALYTIC_PROJECTOR_SEMIGROUP_RECONSTRUCTION_WITHOUT_PRIMARY_SOLVER_TRAJECTORY','pass':passed,'checks':checks,'formula':'p(s)=u+e^-s(p0-u)','claim_boundary_checked':True}
    writej(RUN/'independent'/'INDEPENDENT_RECONSTRUCTION.json',rec)
    (RUN/'INDEPENDENT_VERIFICATION.md').write_text('# Independent Verification — D-130\n\nResult: **PASS**.\n\nAn independent analytic reconstruction used only the exact frozen C parent and the frozen D law. It reconstructed the normalized zero-sum projector, the closed-form semigroup `p(s)=u+exp(-s)(p0-u)`, charge conservation, positivity, monotonic entropy increase, the dimensionless no-loss energy ledger, and the final state without trusting the configured solver trajectory or its PASS flags. The final analytic state matched the primary analytic record exactly within numerical representation tolerance. No public observational values, dimensionful temperature, physical duration, metric expansion, calibrated rates, or empirical identities were introduced.\n',encoding='utf-8')
    return rec

def replay_clean(spec,p0,primary):
    # A clean independent numerical replay of the frozen law in a temporary directory.
    tmp=Path(tempfile.mkdtemp(prefix='d130-replay-'))
    try:
        def rhs(s,p): return np.mean(p)-p
        sol=solve_ivp(rhs,(0,1),p0,method='BDF',rtol=1e-9,atol=1e-12,max_step=.015625)
        exact=np.asarray(analytic(p0,1.0)); err=float(np.linalg.norm(sol.y[:,-1]-exact))
        rec={'result':'PASS' if sol.success and err<=1e-8 else 'FAIL','clean_checkout':True,'artifact_hashes_match':bool(err<=1e-8),'replay_method':'TEMPORARY_CLEAN_EXECUTION_DIRECTORY_FROM_FROZEN_PARENT_AND_SPEC','final_l2_error_vs_frozen_analytic':err,'primary_analytic_sha256':hashlib.sha256(json.dumps(primary['analytic_final'],sort_keys=True).encode()).hexdigest(),'replay_analytic_sha256':hashlib.sha256(json.dumps(exact.tolist(),sort_keys=True).encode()).hexdigest()}
        rec['artifact_hashes_match']=rec['artifact_hashes_match'] and rec['primary_analytic_sha256']==rec['replay_analytic_sha256']
        writej(RUN/'REPLAY_RECORD.json',rec); return rec
    finally: shutil.rmtree(tmp,ignore_errors=True)

def finalize(spec,p0,primary,ind,replay):
    maxconv=max(x['final_l2_error_vs_analytic'] for x in primary['convergence'])
    event_times=[x['s'] for x in spec['events']]
    gates={
      'positive distributions':1.0 if primary['minimum_population']>=-1e-12 else 0.0,
      'energy/charge conservation':1.0 if primary['charge_max_abs_drift']<=1e-9 and primary['dimensionless_total_energy_max_abs_drift']<=1e-9 else 0.0,
      'event ordering':1.0 if event_times==sorted(event_times) and len(set(event_times))==len(event_times) else 0.0,
      'stiff-solver convergence':1.0 if maxconv<=1e-8 and all(x['success'] for x in primary['convergence']) else 0.0,
      'restart and independent reconstruction':1.0 if primary['restart']['final_l2_error_vs_analytic']<=1e-8 and ind['pass'] and replay['result']=='PASS' else 0.0}
    overall='PASS' if min(gates.values())>=.95 else 'FAIL'
    writej(RUN/'GATE_RESULTS.json',{'module':'D','overall':overall,'component_scores':gates,'minimum_component_score':min(gates.values()),'threshold':.95,'aggregate_scores_cannot_override':True,'frozen_science_changed_after_lock':False})
    handoff={'schema_version':'1.0','object_id':'H_D_to_E','from_module':'D','to_module':'E','run_id':RUN_ID,'evidence_state':'FROZEN_PENDING_CONTROLLER_PROMOTION','fidelity':'MINIMAL_SPINE','generation_mode':'GENERATION_SEALED','parent':{'object_id':'H_C_to_D','path':'modules/C/frozen/H_C_to_D.json','sha256':sha(PARENT)},'transport_law':spec['derived_law'],'distribution_history':primary['history'],'entropy_gain_over_one_intrinsic_e_fold':primary['entropy_gain'],'events':spec['events'],'phase_status':spec['phase_status'],'dimensionful_temperature_status':spec['thermal_coordinate']['dimensionful_temperature'],'physical_time_status':'NOT_DERIVED','metric_expansion_status':spec['expansion_status'],'charge_conservation_residual':primary['charge_max_abs_drift'],'dimensionless_energy_ledger_residual':primary['dimensionless_total_energy_max_abs_drift'],'uncertainty':json.loads((RUN/'UNCERTAINTY_COVARIANCE.json').read_text()),'restart':primary['restart'],'independent_verification':ind,'e_readiness':{'distribution_and_intrinsic_clock':'DERIVED','dimensionful_temperature':'NOT_DERIVED','dimensionful_reaction_rates':'NOT_DERIVED','primordial_abundances':'NOT_DERIVED_RESERVED_FOR_E'},'claim_boundary':spec['claim_boundary']}
    hp=ROOT/'modules'/'D'/'frozen'/'H_D_to_E.json'; writej(hp,handoff)
    # environment after execution dependencies are known
    writej(RUN/'ENVIRONMENT.json',{'status':'FINAL','hidden_defaults_audited':True,'python':sys.version,'platform':platform.platform(),'numpy':np.__version__,'generation_mode':'GENERATION_SEALED','network_calls_used_for_science':False,'public_data_used':False,'solver_defaults':{'method':'BDF','rtol':1e-9,'atol':1e-12,'max_step':.015625},'audit_note':'All scientific coefficients and initial conditions came from the exact frozen C parent or the frozen D derivation. Numerical tolerances are implementation controls, not fitted science.'})
    # claim and closeout
    supported='The exact frozen C microscopic parent generates a positive, conserved, source-owned dimensionless nonequilibrium relaxation history under the normalized C projector, with monotonic Shannon entropy growth, an intrinsic collision-count clock, ordered internal relaxation events, a no-loss dimensionless disequilibrium-energy/RFL-memory ledger, converged BDF execution, restart, clean replay, and independent analytic reconstruction at MINIMAL_SPINE fidelity.'
    unsupported='No dimensionful temperature or energy scale, physical duration, metric expansion/scale factor, calibrated collision rate, nontrivial finite phase transition, primordial abundance network, Standard Model identification, or empirical correspondence has been derived.'
    close=f'''# Module D Closeout — {RUN_ID}\n\n## Result\n\nPASS at `MINIMAL_SPINE` within the frozen D claim boundary.\n\n## Strongest supported claim\n\n{supported}\n\n## Strongest unsupported claim\n\n{unsupported}\n\n## Scientific result\n\nThe exact C matrix obeys `M_C/g_C = I - 11^T/3` to numerical representation tolerance, so D inherits a unique source-owned symmetric redistribution generator. With intrinsic clock `s=g_C tau`, the law is `dp/ds=-(I-11^T/3)p` and has the exact solution `p(s)=u+exp(-s)(p(0)-u)`. The evolution is a convex mixture of the inherited positive state and the uniform conserved mode, so positivity and total carrier conservation are structural rather than fitted. Shannon entropy increases toward `ln 3`. A dimensionless disequilibrium energy is transferred exactly into an RFL memory reservoir so the combined dimensionless ledger is conserved.\n\nNo physical temperature, physical time, or metric expansion was manufactured: the C handoff contains no dimensionful energy scale or geometry. The D handoff records those as explicit obstructions. No finite nontrivial thermodynamic phase transition occurs in the frozen linear exact-degenerate minimal spine; only ordered intrinsic relaxation witnesses are claimed.\n\nAll five mandatory component gates scored 1.0000. The configured BDF solver, time-step refinement, restart, analytic reconstruction, countermodels, and clean replay passed without changing the frozen science.\n'''
    (RUN/'CLOSEOUT.md').write_text(close,encoding='utf-8')
    # artifact registry entry for handoff, replacing prior D handoff if any
    rp=ROOT/'memory'/'ARTIFACT_REGISTRY.json'; reg=json.loads(rp.read_text()); reg['artifacts']=[x for x in reg.get('artifacts',[]) if not (x.get('kind')=='MODULE_HANDOFF' and x.get('path')=='modules/D/frozen/H_D_to_E.json')]; reg['artifacts'].append({'path':'modules/D/frozen/H_D_to_E.json','sha256':sha(hp),'kind':'MODULE_HANDOFF','created_utc':now(),'work_unit':'D-130','run_id':RUN_ID}); writej(rp,reg)
    # output manifest only after scientific outputs stop changing
    outs=[]
    for p in [RUN/'FROZEN_DERIVATION_SPEC.json',RUN/'SOURCE_REGISTER.json',RUN/'PRE_EXECUTION_LOCK.json',RUN/'solver_outputs/transport/result.json',RUN/'primary/D_THERMAL_HISTORY.json',RUN/'COUNTERMODELS.json',RUN/'UNCERTAINTY_COVARIANCE.json',RUN/'CHECKPOINT_RECORD.json',RUN/'independent/INDEPENDENT_RECONSTRUCTION.json',RUN/'INDEPENDENT_VERIFICATION.md',RUN/'GATE_RESULTS.json',RUN/'REPLAY_RECORD.json',hp]:
        outs.append({'path':str(p.relative_to(ROOT)),'sha256':sha(p),'bytes':p.stat().st_size})
    writej(RUN/'GENERATED_OUTPUT_MANIFEST.json',{'status':'FINAL','finalized_utc':now(),'outputs':outs})
    return supported,unsupported

def main():
    par,spec,p0,g=derive(); lock_and_bind(spec,p0)
    primary=run_primary(spec,p0); ind=independent(spec,p0,primary); replay=replay_clean(spec,p0,primary); supported,unsupported=finalize(spec,p0,primary,ind,replay)
    print(json.dumps({'run_id':RUN_ID,'spec_sha256':sha(RUN/'FROZEN_DERIVATION_SPEC.json'),'parent_sha256':sha(PARENT),'doublet_gap':g,'supported':supported,'unsupported':unsupported},indent=2))
if __name__=='__main__': main()
